#!/usr/bin/node

const { exit } = require("process");
const yaml = require('js-yaml');


if(process.argv[2]) {

    const { exec } = require("child_process");
    const {readFile} = require('fs');




    function errorHandling(error,stderr){
        if (error) {
            console.warn(`error: ${error.message}`);
            return;
        }
        if (stderr) {
            console.warn(`stderr: ${stderr}`);
            return;
        }
    }

    function bar(options) {
        const optionsstr = []
        for (const key in options) {
            optionsstr.push(key)
        }
        
        exec(`echo "${optionsstr.join("\n")}" | dmenu`, (error, stdout, stderr) => {
            errorHandling(error,stderr)
            const filteredfoo = options[stdout.replace(/\n/g,'')]

            if(typeof filteredfoo === "object"){
                bar(filteredfoo)
            }else{
                exec(`${filteredfoo}`, (error, stdout, stderr) => {
                    errorHandling(error,stderr);
                    console.log(stdout);
                    exit();
                })
            }
        });
    }


    readFile(process.argv[2], 'utf8', (err, data) => {
        if (err) {
        console.error(err);
        return;
        }
        try {
            const foo = yaml.load(data)
            bar(foo)

        
        } catch (error) {
            console.log(error)
        }

    });
    
}else{
    console.log("no input file")
}